name: Release Build

on:
  push:
    tags:
      - 'v*'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        # Create swapfile
        if [ -f /swapfile ]; then
            sudo swapoff /swapfile 2>/dev/null || true
        fi
        sudo dd if=/dev/zero of=/swapfile bs=1M count=4096
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -g

        docker login  --username=${{ secrets.HARBOR_PUSH_USERNAME }} --password=${{ secrets.HARBOR_PUSH_PASSWORD }} harbor.cncfstack.com
        docker buildx create --name mybuilder --use
        for openclaw in 2026.3.12 2026.3.12; do
          sed -i "s/VERSION_TAG/v${openclaw}-${{ github.ref_name }}/g" login/login.html
          docker buildx build --platform linux/amd64,linux/arm64 --build-arg OPENCLAW_VERSION=${openclaw} --push . --file Dockerfile --tag harbor.cncfstack.com/cncfstack/openclaw-in-docker:v${openclaw}-${{ github.ref_name }}
        done