name: Release Build

on:
  push:
    tags:
      - 'v0.1.0-v2026.3.8'
      - 'v0.1.0-v2026.3.7'
      - 'v0.1.0-v2026.3.2'
      - 'v0.1.0-v2026.3.1'
      - 'v0.1.0-v2026.2.26'
      - 'v0.1.0-v2026.2.25'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        # Create swapfile
        sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -g

        docker login  --username=${{ secrets.HARBOR_PUSH_USERNAME }} --password=${{ secrets.HARBOR_PUSH_PASSWORD }} harbor.cncfstack.com
        docker buildx create --name mybuilder --use
        docker buildx build --platform linux/amd64,linux/arm64 --push . --file Dockerfile --tag harbor.cncfstack.com/cncfstack/openclaw-in-docker:v0.1.0-v2026.3.2
